modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/Caupona/issues"
[[mods]] #mandatory
modId = "caupona" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Caupona" #mandatory
authors = "[TeamMoeg] khjxiaogu, Lyuuke"
description = '''
Cook anything into stew
'''
[[dependencies.caupona]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.20)"
    ordering = "NONE"
    side = "BOTH"